from django.db import models

# Create your models here.
class Landmark(models.Model):
    name = models.CharField(max_length=100)
    address = models.CharField(max_length=200)
    latitude = models.FloatField(blank=True, null=True,)
    longitude = models.FloatField(blank=True, null=True,)
    description = models.TextField(blank=True, null=True,)
    # other fields as needed

class Propertym(models.Model):
    encId = models.CharField(blank=True, null=True,max_length=50)
    possStatusD = models.CharField(blank=True, null=True,max_length=50)
    pmtSource = models.CharField(blank=True, null=True,max_length=50)
    url = models.TextField(blank=True, null=True)
    noBfCt = models.CharField(blank=True, null=True,max_length=100)
    st = models.CharField(blank=True, null=True,max_length=100)
    lCtDate = models.TextField(blank=True, null=True)
    appSub = models.CharField(blank=True, null=True,max_length=2)
    sendbirdId = models.CharField(blank=True, null=True,max_length=100)
    lastAccessDate = models.TextField(blank=True, null=True)
    projectSocietyLink = models.CharField(blank=True, null=True,max_length=100)
    sipro = models.CharField(blank=True, null=True,max_length=100)
    appExc = models.CharField(blank=True, null=True,max_length=2)
    cScore = models.CharField(blank=True, null=True,max_length=4)
    devName = models.CharField(blank=True, null=True,max_length=100)
    postDateT = models.CharField(blank=True, null=True,max_length=100)
    endDateT = models.CharField(blank=True, null=True,max_length=100)
    pl = models.CharField(blank=True, null=True,max_length=100)
    floorD = models.TextField(blank=True, null=True)
    floorNo = models.TextField(blank = True, null=True)
    floors = models.CharField(blank=True, null=True,max_length=10)
    luxAmenities = models.TextField(blank=True, null=True)
    luxAmenitiesD  = models.TextField(blank=True, null=True)
    appovedAuthC = models.CharField(blank=True, null=True,max_length=100)
    nriPref = models.CharField(blank=True, null=True,max_length=2)
    availUnit = models.IntegerField(blank=True, null=True,)
    cowDays = models.IntegerField(blank=True, null=True,)
    price = models.IntegerField(blank=True, null=True,)
    priceD = models.CharField(blank=True, null=True,max_length=100)
    imgCt = models.IntegerField(blank=True, null=True,)
    landmarkDetails= models.TextField(blank=True, null=True)
    propertyImageNew = models.TextField(blank=True, null=True)
    psmImage = models.TextField(blank=True, null=True)
    seoDesc = models.TextField(blank=True, null=True)
    pmtmtrendpercentage = models.IntegerField(blank=True, null=True,)
    flooringTyD = models.TextField(blank=True, null=True)
    powerStatusD = models.TextField(blank=True, null=True)
    maintenanceD = models.TextField(blank=True, null=True)
    cg = models.CharField(blank=True, null=True,max_length=2)
    maintenanceCharges = models.CharField(blank=True, null=True,max_length=10)
    bookingAmtExact = models.CharField(blank=True, null=True,max_length=10)
    landmark = models.TextField(blank=True, null=True)
    lCct = models.CharField(blank=True, null=True,max_length=50)
    seoLtSc = models.IntegerField(blank=True, null=True)
    caSqFt = models.FloatField(blank=True, null=True)
    ltcoordGeo = models.CharField(blank=True, null=True,max_length=50)
    lt = models.FloatField(blank=True, null=True)
    loc = models.FloatField(blank=True, null=True)
    dtldesc = models.TextField(blank=True, null=True)
    plgdtldesc = models.TextField(blank=True, null=True)
    oname = models.TextField(blank=True, null=True)
    companyname = models.TextField(blank=True, null=True)
    contName = models.TextField(blank=True, null=True)
    auto_desc = models.TextField(blank=True, null=True)
    prjname = models.TextField(blank=True, null=True)
    sqFtPrD = models.IntegerField(blank=True, null=True,)
    carpetArea = models.CharField(blank=True, null=True,max_length=20)
    isPaidUser = models.CharField(blank=True, null=True,max_length=2)
    ctVerifd = models.CharField(blank=True, null=True,max_length=2)
    pmtLat = models.FloatField(blank=True, null=True)
    pmtLong = models.FloatField(blank=True, null=True)
    moisd = models.CharField(blank=True, null=True,max_length=5)
    imageDate = models.CharField(blank=True, null=True,max_length=20)
    supV = models.CharField(blank=True, null=True,max_length=2)
    lmtDname = models.CharField(blank=True, null=True,max_length=50)
    tag = models.CharField(blank=True, null=True,max_length=50)
    tagWap = models.CharField(blank=True, null=True,max_length=50)
    locSeoName = models.CharField(blank=True, null=True,max_length=50)
    propImg = models.CharField(blank=True, null=True,max_length=100)
    coverAreaUnitD = models.CharField(blank=True, null=True,max_length=20)
    soc = models.CharField(blank=True, null=True,max_length=2)
    prm = models.CharField(blank=True, null=True,max_length=2)
    sqFtPrice = models.FloatField(blank=True, null=True,)
    showupfront = models.CharField(blank=True, null=True,max_length=2)
    caCompNameD = models.TextField(blank=True, null=True)
    postedLabelD = models.TextField(blank=True, null=True)
    OwnershipTypeD = models.CharField(blank=True, null=True,max_length=50)
    furnishedD = models.CharField(blank=True, null=True,max_length=50)
    balconiesD = models.CharField(blank=True, null=True,max_length=10)
    bathD = models.CharField(blank=True, null=True,max_length=10)
    parkingD = models.CharField(blank=True, null=True,max_length=50)
    facingD = models.CharField(blank=True, null=True,max_length=20)
    amenFacingD = models.CharField(blank=True, null=True,max_length=50)
    transactionTypeD = models.CharField(blank=True, null=True,max_length=50)
    propTypeD = models.CharField(blank=True, null=True,max_length=50)
    ctName = models.CharField(blank=True, null=True,max_length=50)
    bedroomD = models.CharField(blank=True, null=True,max_length=10)
    userType = models.CharField(blank=True, null=True,max_length=50)
    transType = models.CharField(blank=True, null=True,max_length=50)
    isPreferred = models.CharField(blank=True, null=True,max_length=10)
    agentDetailUrl = models.CharField(blank=True, null=True,max_length=200)
    is_prime_listing_type = models.BooleanField(blank=True, null=True,default=False)
    dImgRf = models.CharField(blank=True, null=True,max_length=20)
    locality_photo = models.BooleanField(blank=True, null=True,default=False)
    defaultAdddressGoogle = models.CharField(blank=True, null=True,max_length=50)
    propertyTitle = models.CharField(blank=True, null=True,max_length=200)
    crisilRv1CtBy = models.CharField(blank=True, null=True,max_length=50)
    crisilNoOfEmployees = models.IntegerField(blank=True, null=True,)
    crisilStarRating = models.IntegerField(blank=True, null=True,)
    crisilOpSinceYear = models.BigIntegerField(blank=True, null=True,default=0)
    postedEditedLabel = models.CharField(blank=True, null=True,max_length=20)
    wapImgUrl = models.CharField(blank=True, null=True,max_length=200)
    wapImgUrl1 = models.CharField(blank=True, null=True,max_length=200)
    seoURL = models.CharField(blank=True, null=True,max_length=200)
    waterStatus = models.CharField(blank=True, null=True,max_length=100)
    isLuxury = models.CharField(blank=True, null=True,max_length=1)
    coveredArea = models.TextField(blank=True, null=True)
    covAreaUnit = models.CharField(blank=True, null=True,max_length=10)
    carpAreaUnit = models.CharField(blank=True, null=True,max_length=10)
    image = models.CharField(blank=True, null=True,max_length=200)
    actualOwner = models.CharField(blank=True, null=True,max_length=10)
    amenities = models.TextField(blank=True, null=True)
    isProjProp = models.CharField(blank=True, null=True,max_length=1)
    devId = models.IntegerField(blank=True, null=True,)
    pglmtkey = models.CharField(blank=True, null=True,max_length=20)
    psmapproved = models.CharField(blank=True, null=True,max_length=10)
    sortCode26 = models.FloatField(blank=True, null=True,)
    ubicnt = models.CharField(blank=True, null=True,max_length=50)
    endDt = models.CharField(blank=True, null=True,max_length=20)
    ranPropImg = models.TextField(blank=True, null=True,)
    newUrl = models.TextField(blank=True, null=True)
    catAdd1 = models.TextField(blank=True, null=True)
    operatingSinceYear = models.CharField(blank=True, null=True,max_length=4)
    tenantsPreference = models.CharField(blank=True, null=True,max_length=20)
    isThisListingAPremiumOnly = models.BooleanField(blank=True, null=True,)
    isAdvertiserOfThisListingAOwnerAndUnPaid = models.BooleanField(blank=True, null=True,)
    isCardDesc = models.BooleanField(blank=True, null=True,)
    scdcattype = models.TextField(blank=True, null=True)
    scdloc = models.TextField(blank=True, null=True)
    scdpropdesc = models.TextField(blank=True, null=True)
    scdimgalt = models.TextField(blank=True, null=True)
    covAreaUnitDesc = models.CharField(blank=True, null=True,max_length=10)
    investorlisting = models.CharField(blank=True, null=True,max_length=1)
    investorguide = models.CharField(blank=True, null=True,max_length=1)
    ampDesc = models.TextField(blank=True, null=True,)
    b2cCardEligibility = models.BooleanField(blank=True, null=True,)
    maskedMobileNumber = models.CharField(blank=True, null=True,max_length=15)
    isLuxuryServiceAvailable = models.BooleanField(blank=True, null=True,)
    luxAmenMap = models.JSONField(blank=True, null=True,)
    nonluxAmenMap = models.JSONField(blank=True, null=True,)








