# Generated by Django 4.1.7 on 2023-02-18 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("propertym", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="propertym", name="modifiedDate",),
    ]
