# Generated by Django 4.1.7 on 2023-02-18 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("propertym", "0003_rename_maintainencecharges_propertym_maintenancecharges"),
    ]

    operations = [
        migrations.AlterField(
            model_name="propertym",
            name="luxAmenities",
            field=models.TextField(blank=True, null=True),
        ),
    ]
