# Generated by Django 4.1.7 on 2023-02-18 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("propertym", "0004_alter_propertym_luxamenities"),
    ]

    operations = [
        migrations.AlterField(
            model_name="propertym",
            name="luxAmenitiesD",
            field=models.TextField(blank=True, null=True),
        ),
    ]
