# Generated by Django 4.1.7 on 2023-02-18 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("propertym", "0005_alter_propertym_luxamenitiesd"),
    ]

    operations = [
        migrations.AlterField(
            model_name="propertym",
            name="floorNo",
            field=models.TextField(blank=True, null=True),
        ),
    ]
