# Generated by Django 4.1.7 on 2023-02-18 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("propertym", "0006_alter_propertym_floorno"),
    ]

    operations = [
        migrations.AlterField(
            model_name="propertym",
            name="prjname",
            field=models.TextField(blank=True, null=True),
        ),
    ]
